[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_twitter = "8HQysmoxq6rfMKkhTnbQ6AVeu9nXKyC3PCea3DkQh5o9"

[programs.devnet]
solana_twitter = "8HQysmoxq6rfMKkhTnbQ6AVeu9nXKyC3PCea3DkQh5o9"

[registry]
url = "https://api.apr.dev"



[provider]
cluster = "devnet"
wallet = "/home/valter/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello world!'"
